spring:
  application:
    name: menu-service
  flyway:
    locations: classpath:/db/migration/core
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mappers/*.xml
